[package]
name = "base-rust-web-api"
version = "0.1.0"
edition = "2024"

[dependencies]
trpl = "0.3.0"
tokio = { version = "1", features = ["rt", "net", "io-util"] }
chrono = "0.4.43"
dotenv = "0.15.0"
